### ISSUE TITLE
"In Development" section on main page

### ISSUE THREAD

**Issue by thekerp** [lexDAO/landing-page#11]
Thinking they link to github?

<img width="530" alt="Screen Shot 2020-05-21 at 3 08 50 PM" src="https://user-images.githubusercontent.com/2836619/82615156-9539d000-9b7e-11ea-9feb-3306bda04ed3.png">

**Comment by Ro5s** [comment]
Yeah, I like github as source o' truth on our developments @thekerp 

- LexToken ✔️  - https://github.com/lexDAO/LexToken

In Development (Not Certified): 
- LexSecurity Token - https://github.com/lexDAO/Security-Token
- LexLocker for Digital Deals - https://github.com/lexDAO/Escrow

**Comment by thekerp** [comment]
Sweet. I'll get those in there @Ro5s

**Comment by thekerp** [comment]
Oh yeah, I pulled these out of the design. I guess we could get them back in, but not critical for launch. I'll get them in there.
