### ISSUE TITLE
Lexdao.club redirect

### ISSUE THREAD

**Issue by thekerp** [lexDAO/landing-page#12]
First step: clear out conflicts and point "@" A record pointed to 104.198.14.52

Second step: unlink other netlify account

**Comment by Ro5s** [comment]
cheers! I was able to get into my godaddy account finally ~ let me know what this needs 2 cross finish line @thekerp

**Comment by thekerp** [comment]
Sweet! @Ro5s getting this now:

<img width="726" alt="Screen Shot 2020-05-24 at 11 46 15 AM" src="https://user-images.githubusercontent.com/2836619/82762141-2f368e00-9db4-11ea-89f0-785947618c05.png">

so, looks like we need to get someone within Netlify (or with their netlify account) to turn that off...

Also, should we be putting this to a vote before making the change?

**Comment by thekerp** [comment]
do we still want to do this now that we have .org set up?
